/**
 * GUI controls IDs.
 *
 * \author Allann Jones
 */

#ifndef GUI_CONTROLS_HPP
#define GUI_CONTROLS_HPP

/**
 * Unique identifier for graphical controls.
 */
typedef enum {
    GUI_CONTROL_BASE_ID = 1,  /**< Main User dialog window ID. **/

    FRAME_MAIN_ID,

    PANEL_AUDIO_TOOLBAR_LOAD_FILE_ID,
    PANEL_AUDIO_TOOLBAR_LIST_CLEAN_ID,
    PANEL_AUDIO_LISTCTRL_AUDIO_ID,
    PANEL_AUDIO_TOOLBAR_AUDIO_NEW_ID,

    DLG_AUDIO_CONTROL_BTN_PLAY_START_ID,
    DLG_AUDIO_CONTROL_BTN_STOP_ID,
    DLG_AUDIO_CONTROL_BTN_PAUSE_ID,

    CANVAS_AUDIO_PLOT_CANVAS_ID,

    DLG_AUDIO_CONTROL_BTN_RECORD_SAVE_ID,
    DLG_AUDIO_CONTROL_BTN_RECORD_START_ID,
    DLG_AUDIO_CONTROL_BTN_RECORD_PAUSE_ID,
    DLG_AUDIO_CONTROL_BTN_RECORD_STOP_ID
} GUIControl_ID_t;

#endif /* GUI_CONTROLS_HPP */
